-- ============================================================
-- RBAC SYSTEM — SNOWFLAKE EXECUTION SCRIPT
-- AI-Powered Data Platform — Enterprise Grade
-- ============================================================
-- Run as: ORG_ADMIN or SYSADMIN
-- Environment: DEV / QA / PROD (adapt DB/warehouse names per env)
-- ============================================================
USE ROLE ACCOUNTADMIN;
-- ============================================================
-- RBAC SYSTEM — SNOWFLAKE EXECUTION SCRIPT
-- AI-Powered Data Platform — Enterprise Grade
-- ============================================================
-- Run as: ORG_ADMIN or SYSADMIN
-- Environment: DEV / QA / PROD (adapt DB/warehouse names per env)
-- ============================================================

-- ============================================================
-- SECTION 1: CREATE ROLES
-- ============================================================
CREATE ROLE IF NOT EXISTS ORG_ADMIN;
CREATE ROLE IF NOT EXISTS SECURITY_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ANALYTICS_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS BUSINESS_USER;
CREATE ROLE IF NOT EXISTS VIEWER;
CREATE ROLE IF NOT EXISTS SYSTEM_AGENT;

-- ============================================================
-- SECTION 2: ROLE HIERARCHY GRANTS
-- ============================================================
GRANT ROLE ORG_ADMIN          TO ROLE SYSADMIN;
GRANT ROLE SECURITY_ADMIN     TO ROLE ORG_ADMIN;
GRANT ROLE DATA_ENGINEER      TO ROLE ORG_ADMIN;
GRANT ROLE ANALYTICS_ENGINEER TO ROLE DATA_ENGINEER;
GRANT ROLE DATA_SCIENTIST     TO ROLE ANALYTICS_ENGINEER;
GRANT ROLE BUSINESS_USER      TO ROLE DATA_SCIENTIST;
GRANT ROLE VIEWER             TO ROLE BUSINESS_USER;
GRANT ROLE SYSTEM_AGENT       TO ROLE ORG_ADMIN;

-- ============================================================
-- SECTION 3: WAREHOUSE GRANTS
-- ============================================================
-- Ensure required warehouses exist before grants.
-- Requires SYSADMIN (or ACCOUNTADMIN) privileges for CREATE WAREHOUSE.
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- COMPUTE_WH: General-purpose query warehouse
GRANT ALL     ON WAREHOUSE COMPUTE_WH   TO ROLE ORG_ADMIN;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE SECURITY_ADMIN;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE DATA_ENGINEER;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE DATA_SCIENTIST;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE BUSINESS_USER;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE VIEWER;
GRANT USAGE   ON WAREHOUSE COMPUTE_WH   TO ROLE SYSTEM_AGENT;

-- TRANSFORM_WH: Pipeline and transformation warehouse
GRANT ALL          ON WAREHOUSE TRANSFORM_WH TO ROLE ORG_ADMIN;
GRANT USAGE, MODIFY ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER;
GRANT USAGE        ON WAREHOUSE TRANSFORM_WH TO ROLE ANALYTICS_ENGINEER;

-- ============================================================
-- SECTION 4: DATABASE GRANTS
-- ============================================================
-- Ensure required databases/schemas exist before grants.
-- Requires SYSADMIN (or ACCOUNTADMIN) privileges for CREATE DATABASE/SCHEMA.
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE DATABASE IF NOT EXISTS STAGING_DB;
CREATE DATABASE IF NOT EXISTS CURATED_DB;
CREATE DATABASE IF NOT EXISTS SANDBOX_DB;
CREATE DATABASE IF NOT EXISTS PUBLISHED_DB;
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB;

CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.SECURITY;

-- RAW_DB: Ingestion layer
GRANT USAGE                     ON DATABASE RAW_DB TO ROLE ORG_ADMIN;
GRANT USAGE                     ON DATABASE RAW_DB TO ROLE DATA_ENGINEER;
GRANT USAGE                     ON DATABASE RAW_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE                     ON DATABASE RAW_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE                     ON DATABASE RAW_DB TO ROLE SYSTEM_AGENT;

GRANT ALL    ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE DATA_ENGINEER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE SYSTEM_AGENT;

GRANT SELECT, INSERT ON ALL TABLES IN DATABASE RAW_DB TO ROLE DATA_ENGINEER;
GRANT SELECT         ON ALL TABLES IN DATABASE RAW_DB TO ROLE ANALYTICS_ENGINEER;
GRANT SELECT         ON ALL TABLES IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST;
GRANT SELECT         ON ALL TABLES IN DATABASE RAW_DB TO ROLE SYSTEM_AGENT;

-- STAGING_DB: Cleaning and transformation layer
GRANT USAGE  ON DATABASE STAGING_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON DATABASE STAGING_DB TO ROLE DATA_ENGINEER;
GRANT USAGE  ON DATABASE STAGING_DB TO ROLE ANALYTICS_ENGINEER;

GRANT ALL    ON ALL SCHEMAS IN DATABASE STAGING_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE STAGING_DB TO ROLE DATA_ENGINEER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE STAGING_DB TO ROLE ANALYTICS_ENGINEER;

GRANT ALL           ON ALL TABLES IN DATABASE STAGING_DB TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT ON ALL TABLES IN DATABASE STAGING_DB TO ROLE ANALYTICS_ENGINEER;

-- CURATED_DB: Business-ready analytics layer
GRANT USAGE  ON DATABASE CURATED_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON DATABASE CURATED_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE  ON DATABASE CURATED_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE  ON DATABASE CURATED_DB TO ROLE BUSINESS_USER;
GRANT USAGE  ON DATABASE CURATED_DB TO ROLE SYSTEM_AGENT;

GRANT ALL    ON ALL SCHEMAS IN DATABASE CURATED_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE CURATED_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE CURATED_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE CURATED_DB TO ROLE BUSINESS_USER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE CURATED_DB TO ROLE SYSTEM_AGENT;

GRANT ALL    ON ALL TABLES IN DATABASE CURATED_DB TO ROLE ANALYTICS_ENGINEER;
GRANT SELECT ON ALL TABLES IN DATABASE CURATED_DB TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL VIEWS  IN DATABASE CURATED_DB TO ROLE BUSINESS_USER;
GRANT SELECT ON ALL VIEWS  IN DATABASE CURATED_DB TO ROLE SYSTEM_AGENT;

-- SANDBOX_DB: Data scientist experimentation
GRANT USAGE  ON DATABASE SANDBOX_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST;

GRANT ALL    ON ALL SCHEMAS IN DATABASE SANDBOX_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST;

GRANT ALL    ON ALL TABLES IN DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST;

-- PUBLISHED_DB: Published views and dashboards
GRANT USAGE  ON DATABASE PUBLISHED_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;
GRANT USAGE  ON DATABASE PUBLISHED_DB TO ROLE VIEWER;

GRANT ALL    ON ALL SCHEMAS IN DATABASE PUBLISHED_DB TO ROLE ORG_ADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE PUBLISHED_DB TO ROLE VIEWER;

GRANT SELECT ON ALL VIEWS IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;
GRANT SELECT ON ALL VIEWS IN DATABASE PUBLISHED_DB TO ROLE VIEWER;

-- GOVERNANCE_DB: Audit and security schemas
GRANT ALL    ON DATABASE GOVERNANCE_DB TO ROLE ORG_ADMIN;
GRANT ALL    ON DATABASE GOVERNANCE_DB TO ROLE SECURITY_ADMIN;

-- ============================================================
-- SECTION 5: FUTURE GRANTS (auto-apply to new objects)
-- ============================================================
GRANT SELECT, INSERT ON FUTURE TABLES IN DATABASE RAW_DB     TO ROLE DATA_ENGINEER;
GRANT SELECT         ON FUTURE TABLES IN DATABASE RAW_DB     TO ROLE ANALYTICS_ENGINEER;
GRANT SELECT         ON FUTURE TABLES IN DATABASE RAW_DB     TO ROLE DATA_SCIENTIST;
GRANT SELECT         ON FUTURE TABLES IN DATABASE RAW_DB     TO ROLE SYSTEM_AGENT;

GRANT ALL            ON FUTURE TABLES IN DATABASE STAGING_DB TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT ON FUTURE TABLES IN DATABASE STAGING_DB TO ROLE ANALYTICS_ENGINEER;

GRANT ALL            ON FUTURE TABLES IN DATABASE CURATED_DB TO ROLE ANALYTICS_ENGINEER;
GRANT SELECT         ON FUTURE TABLES IN DATABASE CURATED_DB TO ROLE DATA_SCIENTIST;
GRANT SELECT         ON FUTURE VIEWS  IN DATABASE CURATED_DB TO ROLE BUSINESS_USER;
GRANT SELECT         ON FUTURE VIEWS  IN DATABASE CURATED_DB TO ROLE SYSTEM_AGENT;

GRANT ALL            ON FUTURE TABLES IN DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST;

GRANT SELECT         ON FUTURE VIEWS  IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;
GRANT SELECT         ON FUTURE VIEWS  IN DATABASE PUBLISHED_DB TO ROLE VIEWER;

-- Future grants for schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DB     TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DB     TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DB     TO ROLE DATA_SCIENTIST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_DB     TO ROLE SYSTEM_AGENT;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE STAGING_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE STAGING_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CURATED_DB TO ROLE ANALYTICS_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CURATED_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CURATED_DB TO ROLE BUSINESS_USER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CURATED_DB TO ROLE SYSTEM_AGENT;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SANDBOX_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PUBLISHED_DB TO ROLE VIEWER;

-- ============================================================
-- SECTION 6: SECURE VIEWS ACCESS
-- ============================================================
GRANT SELECT ON ALL  VIEWS IN DATABASE CURATED_DB   TO ROLE BUSINESS_USER;
GRANT SELECT ON ALL  VIEWS IN DATABASE CURATED_DB   TO ROLE SYSTEM_AGENT;
GRANT SELECT ON ALL  VIEWS IN DATABASE PUBLISHED_DB TO ROLE VIEWER;
GRANT SELECT ON ALL  VIEWS IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;

GRANT SELECT ON FUTURE VIEWS IN DATABASE CURATED_DB   TO ROLE BUSINESS_USER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE CURATED_DB   TO ROLE SYSTEM_AGENT;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PUBLISHED_DB TO ROLE VIEWER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PUBLISHED_DB TO ROLE BUSINESS_USER;

-- ============================================================
-- SECTION 7: DYNAMIC DATA MASKING (PII)
-- ============================================================
CREATE MASKING POLICY IF NOT EXISTS pii_email_mask
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ORG_ADMIN', 'SECURITY_ADMIN') THEN val
    ELSE '***MASKED***'
  END;

CREATE MASKING POLICY IF NOT EXISTS pii_phone_mask
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ORG_ADMIN', 'SECURITY_ADMIN') THEN val
    ELSE REGEXP_REPLACE(val, '[0-9]', 'X')
  END;

CREATE MASKING POLICY IF NOT EXISTS pii_ssn_mask
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ORG_ADMIN', 'SECURITY_ADMIN') THEN val
    ELSE 'XXX-XX-' || RIGHT(val, 4)
  END;

CREATE MASKING POLICY IF NOT EXISTS pii_name_mask
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ORG_ADMIN', 'SECURITY_ADMIN', 'DATA_ENGINEER', 'ANALYTICS_ENGINEER') THEN val
    ELSE LEFT(val, 1) || '****'
  END;

-- Apply masking policies to PII columns (adjust table/column names per environment)
-- ALTER TABLE CURATED_DB.PUBLIC.CUSTOMERS MODIFY COLUMN email   SET MASKING POLICY pii_email_mask;
-- ALTER TABLE CURATED_DB.PUBLIC.CUSTOMERS MODIFY COLUMN phone   SET MASKING POLICY pii_phone_mask;
-- ALTER TABLE CURATED_DB.PUBLIC.CUSTOMERS MODIFY COLUMN ssn     SET MASKING POLICY pii_ssn_mask;
-- ALTER TABLE CURATED_DB.PUBLIC.CUSTOMERS MODIFY COLUMN full_name SET MASKING POLICY pii_name_mask;

-- ============================================================
-- SECTION 8: ROW ACCESS POLICY
-- ============================================================
CREATE ROW ACCESS POLICY IF NOT EXISTS org_row_policy
  AS (org_id STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ORG_ADMIN', 'SECURITY_ADMIN', 'DATA_ENGINEER', 'ANALYTICS_ENGINEER')
  OR org_id = CURRENT_SESSION();

-- Apply row access policy (adjust per environment)
-- ALTER TABLE CURATED_DB.PUBLIC.CUSTOMERS ADD ROW ACCESS POLICY org_row_policy ON (org_id);
-- ALTER TABLE CURATED_DB.PUBLIC.TRANSACTIONS ADD ROW ACCESS POLICY org_row_policy ON (org_id);

-- ============================================================
-- SECTION 9: ASSIGN ROLES TO USERS
-- ============================================================
-- Replace <username> with actual Snowflake user names
-- GRANT ROLE ORG_ADMIN          TO USER <org_admin_user>;
-- GRANT ROLE SECURITY_ADMIN     TO USER <security_admin_user>;
-- GRANT ROLE DATA_ENGINEER      TO USER <data_engineer_user>;
-- GRANT ROLE ANALYTICS_ENGINEER TO USER <analytics_engineer_user>;
-- GRANT ROLE DATA_SCIENTIST     TO USER <data_scientist_user>;
-- GRANT ROLE BUSINESS_USER      TO USER <business_user>;
-- GRANT ROLE VIEWER             TO USER <viewer_user>;
-- GRANT ROLE SYSTEM_AGENT       TO USER <agent_service_account>;

-- ============================================================
-- SECTION 10: AUDIT LOGGING & MONITORING
-- ============================================================
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SECURITY_ADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ORG_ADMIN;

-- Create governance audit database and schema
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.SECURITY;

-- Audit log table for RBAC changes
CREATE TABLE IF NOT EXISTS GOVERNANCE_DB.AUDIT.RBAC_AUDIT_LOG (
    audit_id        VARCHAR(255) DEFAULT UUID_STRING() PRIMARY KEY,
    action_type     VARCHAR(50)  NOT NULL,     -- GRANT, REVOKE, ROLE_CREATE, ROLE_DROP
    target_role     VARCHAR(255),
    target_user     VARCHAR(255),
    target_resource VARCHAR(500),
    privilege       VARCHAR(255),
    performed_by    VARCHAR(255) NOT NULL,
    performed_at    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    details         VARIANT
);

-- Role assignment tracking
CREATE TABLE IF NOT EXISTS GOVERNANCE_DB.AUDIT.ROLE_ASSIGNMENTS (
    assignment_id   VARCHAR(255) DEFAULT UUID_STRING() PRIMARY KEY,
    user_name       VARCHAR(255) NOT NULL,
    role_name       VARCHAR(255) NOT NULL,
    assigned_by     VARCHAR(255) NOT NULL,
    assigned_at     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    revoked_by      VARCHAR(255),
    revoked_at      TIMESTAMP_NTZ,
    is_active       BOOLEAN DEFAULT TRUE,
    expires_at      TIMESTAMP_NTZ,
    environment     VARCHAR(50)  -- DEV, QA, PROD
);

-- Agent task scope tracking
CREATE TABLE IF NOT EXISTS GOVERNANCE_DB.AUDIT.AGENT_TASK_LOG (
    task_id         VARCHAR(255) DEFAULT UUID_STRING() PRIMARY KEY,
    agent_id        VARCHAR(255) NOT NULL,
    task_type       VARCHAR(100) NOT NULL,
    target_schema   VARCHAR(500),
    action          VARCHAR(100) NOT NULL,
    query_hash      VARCHAR(255),
    rows_affected   INT,
    status          VARCHAR(50)  NOT NULL,     -- RUNNING, COMPLETED, FAILED, DENIED
    started_at      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at    TIMESTAMP_NTZ,
    error_message   VARCHAR(2000),
    performed_by    VARCHAR(255) NOT NULL
);

-- Indexes for audit queries
-- Snowflake does not support CREATE INDEX for standard tables.
-- Optional acceleration with Search Optimization Service:
-- ALTER TABLE GOVERNANCE_DB.AUDIT.RBAC_AUDIT_LOG ADD SEARCH OPTIMIZATION ON EQUALITY(action_type, performed_by);
-- ALTER TABLE GOVERNANCE_DB.AUDIT.ROLE_ASSIGNMENTS ADD SEARCH OPTIMIZATION ON EQUALITY(user_name, role_name);
-- ALTER TABLE GOVERNANCE_DB.AUDIT.AGENT_TASK_LOG ADD SEARCH OPTIMIZATION ON EQUALITY(agent_id, status);

-- ============================================================
-- SECTION 11: VERIFICATION QUERIES
-- ============================================================
-- Run these after setup to verify grants:
-- SHOW GRANTS TO ROLE DATA_ENGINEER;
-- SHOW GRANTS TO ROLE ANALYTICS_ENGINEER;
-- SHOW GRANTS TO ROLE SYSTEM_AGENT;
-- SHOW GRANTS TO ROLE ORG_ADMIN;
-- SHOW ROLES;
-- SHOW GRANTS TO USER <username>;
